services:
  - type: web
    name: pippa-sprachapp-3woerter
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push
      npm run build
      cp -r public .next/standalone/
      cp -r .next/static .next/standalone/.next/
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DEBUG
        value: "true"
      - key: NEXT_SHARP_PATH
        value: "/usr/local/lib/node_modules/sharp"
      - key: NODE_OPTIONS
        value: "--trace-warnings --trace-uncaught"
      - key: DATABASE_URL
        fromDatabase:
          name: pippa_db
          property: connectionString
      - key: POSTGRES_PRISMA_URL
        fromDatabase:
          name: pippa_db
          property: connectionString
      - key: POSTGRES_URL_NON_POOLING
        fromDatabase:
          name: pippa_db
          property: connectionString

databases:
  - name: pippa_db
    plan: free
    ipAllowList: []
